# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yolo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yolo.proto',
  package='yolo',
  serialized_pb=_b('\n\nyolo.proto\x12\x04yolo\"\xd2\x01\n\tImage_jpg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\t\x12\x10\n\x08\x63hannels\x18\x02 \x02(\x05\x12\r\n\x05width\x18\x03 \x02(\x05\x12\x0e\n\x06height\x18\x04 \x02(\x05\x12&\n\x06object\x18\x05 \x03(\x0b\x32\x16.yolo.Image_jpg.Object\x12\x12\n\nobject_num\x18\x06 \x02(\x05\x1aJ\n\x06Object\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\r\n\x05width\x18\x03 \x02(\x05\x12\x0e\n\x06height\x18\x04 \x02(\x05\x12\x0b\n\x03\x63ls\x18\x05 \x02(\t\"\xe4\x01\n\tImage_raw\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x02(\t\x12\x10\n\x08\x63hannels\x18\x03 \x02(\x05\x12\r\n\x05width\x18\x04 \x02(\x05\x12\x0e\n\x06height\x18\x05 \x02(\x05\x12&\n\x06object\x18\x06 \x03(\x0b\x32\x16.yolo.Image_raw.Object\x12\x12\n\nobject_num\x18\x07 \x02(\x05\x1aJ\n\x06Object\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\r\n\x05width\x18\x03 \x02(\x05\x12\x0e\n\x06height\x18\x04 \x02(\x05\x12\x0b\n\x03\x63ls\x18\x05 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IMAGE_JPG_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='yolo.Image_jpg.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='yolo.Image_jpg.Object.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='yolo.Image_jpg.Object.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='yolo.Image_jpg.Object.width', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='yolo.Image_jpg.Object.height', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cls', full_name='yolo.Image_jpg.Object.cls', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=231,
)

_IMAGE_JPG = _descriptor.Descriptor(
  name='Image_jpg',
  full_name='yolo.Image_jpg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='yolo.Image_jpg.data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channels', full_name='yolo.Image_jpg.channels', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='yolo.Image_jpg.width', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='yolo.Image_jpg.height', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object', full_name='yolo.Image_jpg.object', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_num', full_name='yolo.Image_jpg.object_num', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMAGE_JPG_OBJECT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=231,
)


_IMAGE_RAW_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='yolo.Image_raw.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='yolo.Image_raw.Object.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='yolo.Image_raw.Object.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='yolo.Image_raw.Object.width', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='yolo.Image_raw.Object.height', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cls', full_name='yolo.Image_raw.Object.cls', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=231,
)

_IMAGE_RAW = _descriptor.Descriptor(
  name='Image_raw',
  full_name='yolo.Image_raw',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='yolo.Image_raw.data', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filename', full_name='yolo.Image_raw.filename', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channels', full_name='yolo.Image_raw.channels', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='yolo.Image_raw.width', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='yolo.Image_raw.height', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object', full_name='yolo.Image_raw.object', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_num', full_name='yolo.Image_raw.object_num', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IMAGE_RAW_OBJECT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=462,
)

_IMAGE_JPG_OBJECT.containing_type = _IMAGE_JPG
_IMAGE_JPG.fields_by_name['object'].message_type = _IMAGE_JPG_OBJECT
_IMAGE_RAW_OBJECT.containing_type = _IMAGE_RAW
_IMAGE_RAW.fields_by_name['object'].message_type = _IMAGE_RAW_OBJECT
DESCRIPTOR.message_types_by_name['Image_jpg'] = _IMAGE_JPG
DESCRIPTOR.message_types_by_name['Image_raw'] = _IMAGE_RAW

Image_jpg = _reflection.GeneratedProtocolMessageType('Image_jpg', (_message.Message,), dict(

  Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(
    DESCRIPTOR = _IMAGE_JPG_OBJECT,
    __module__ = 'yolo_pb2'
    # @@protoc_insertion_point(class_scope:yolo.Image_jpg.Object)
    ))
  ,
  DESCRIPTOR = _IMAGE_JPG,
  __module__ = 'yolo_pb2'
  # @@protoc_insertion_point(class_scope:yolo.Image_jpg)
  ))
_sym_db.RegisterMessage(Image_jpg)
_sym_db.RegisterMessage(Image_jpg.Object)

Image_raw = _reflection.GeneratedProtocolMessageType('Image_raw', (_message.Message,), dict(

  Object = _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), dict(
    DESCRIPTOR = _IMAGE_RAW_OBJECT,
    __module__ = 'yolo_pb2'
    # @@protoc_insertion_point(class_scope:yolo.Image_raw.Object)
    ))
  ,
  DESCRIPTOR = _IMAGE_RAW,
  __module__ = 'yolo_pb2'
  # @@protoc_insertion_point(class_scope:yolo.Image_raw)
  ))
_sym_db.RegisterMessage(Image_raw)
_sym_db.RegisterMessage(Image_raw.Object)


# @@protoc_insertion_point(module_scope)
